name = "vhlink"
type = "javascript"
account_id = "0c904c572ba3518d990bd3bcbe592013"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "e24df198c1b04a7abce666e2f986c8d0", preview_id = "e24df198c1b04a7abce666e2f986c8d0" }
]
