name = "linkshortener"
type = "javascript"
account_id = "0c904c572ba3518d990bd3bcbe592013"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-01-01"
kv_namespaces = [
  { binding = "LINKS", id = "dcc3c66c51a44bdaa78090665b36f724", preview_id = "dcc3c66c51a44bdaa78090665b36f724" }
]
